language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t scotchcurry/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true scotchcurry/react-test npm test

after_success:
  - docker build -t scotchcurry/multi-client ./client
  - docker build -t scotchcurry/multi-nginx ./nginx
  - docker build -t scotchcurry/multi-server ./server
  - docker build -t scotchcurry/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push to docker hub
  - docker push scotchcurry/multi-client
  - docker push scotchcurry/multi-nginx
  - docker push scotchcurry/multi-server
  - docker push scotchcurry/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-918532603467'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
